# -*- coding: utf-8 -*-
"""diego_y_santi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKHySzYRoBHox3DEN0rqi84pDtztaNEB
"""

def es_par_o_impar (numero):
  if numero % 2 == 0:
    return "Par"
  else:
    return "Impar"

def saludar_por_nombre():
  nombre=input("ingresar su nombre")
  print("hola",nombre)
  return("hola",nombre)

def calcular_area_circulo (radio):
    area=3.14*radio**2
    return area


def si_numero_es_positivo_o_negativo_o_cero(numero):
  if numero > 0:
    return "positivo"
  elif numero < 0:
    return "negativo"
  else:
    return "cero"

def grados_celsius_a_farenheit(grados_celsius):
  grados_farenheit=(grados_celsius*9/5)+32
  return grados_farenheit

def numero_cuadrado_de_numero(numero):
  numero_cuadrado=numero**2
  return numero_cuadrado

def calcular_factorial_de_numero(numero):
  factorial=1
  for i in range(1,numero+1):
    factorial=factorial*i
  return factorial

def cuantas_vocales_tiene_la_palabra(palabra):
  vocales="aeiou"
  contador=0
  for letra in palabra:
    if letra in vocales:
      contador=contador+1
  return contador

def calcular_area_circulo_y_triangulo_y_rectangulo(base,altura,radio):
  area_circulo=3.14*radio**2
  area_triangulo=base*altura/2
  area_rectangulo=base*altura
  return area_circulo,area_triangulo,area_rectangulo