# -*- coding: utf-8 -*-
"""diego_y_santi_librerias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWGGDAKsZ6SWG_ToYlz5y68-wKNitpTE
"""

import diego_y_santi as falcon
falcon.es_par_o_impar(10)
falcon.saludar_por_nombre()
falcon.calcular_area_circulo(5)
falcon.si_numero_es_positivo_o_negativo_o_cero(-2)
falcon.grados_celsius_a_farenheit(13)
falcon.numero_cuadrado_de_numero(5)
falcon.calcular_factorial_de_numero(67)
falcon.cuantas_vocales_tiene_la_palabra("buenas")
falcon.calcular_area_circulo_y_triangulo_y_rectangulo(3,2,3)